ALTER TABLE reward_codes ADD COLUMN code1 VARCHAR(50) DEFAULT NULL AFTER reward_id;
ALTER TABLE reward_codes ADD COLUMN code2 VARCHAR(50) DEFAULT NULL AFTER code1;
ALTER TABLE reward_codes ADD COLUMN code3 VARCHAR(50) DEFAULT NULL AFTER code2;
ALTER TABLE reward_codes ADD COLUMN code4 VARCHAR(50) DEFAULT NULL AFTER code3;
ALTER TABLE reward_codes ADD COLUMN code5 VARCHAR(50) DEFAULT NULL AFTER code4;
ALTER TABLE reward_codes ADD COLUMN code6 VARCHAR(50) DEFAULT NULL AFTER code5;
UPDATE reward_codes SET code1 = code WHERE code1 IS NULL AND code IS NOT NULL;
ALTER TABLE rewards ADD COLUMN codes_count INT DEFAULT 1 AFTER pdf_template;
